export { default as AppMain } from './AppMain/index.vue'
export { default as Header } from './Header/index.vue'
export { default as Logo } from './Logo/index.vue'
export { default as Menu } from './Menu/index.vue'
export { default as TagsView } from './TagsView/index.vue'
export { default as Trigger } from './Trigger/index.vue'
