export { default as AppMain } from './AppMain/index.vue'
export { default as Header } from './Header/index.vue'
export { default as Logo } from './Logo/index.vue'
export { default as Menu } from './Menu/index.vue'
export { default as Sider } from './Sider/index.vue'
export { default as Tabs } from './Tabs/index.vue'
export { default as Trigger } from './Trigger/index.vue'
